data:
  train_files: Ricky06662/VisionReasoner_multi_object_1k_840
  val_files: None
  prompt_key: problem
  max_prompt_length: 1300
  max_response_length: 2000
  rollout_batch_size: 8
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 8
    micro_batch_size_per_device_for_update: 8
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    is_noisy: false
    aug_type: gaussian
    gaussian_noise_step: 500
    crop_size: 0.0
    rotate_angle: 15
    decay_coef: 1.0
    decay_mode: none
    decay_sig_mid_step: 40
    model:
      model_path: Qwen/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false
      optimizer_offload: false
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true

  rollout:
    temperature: 1.0
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.5
    n: 4
    enable_chunked_prefill: true

  ref:
    offload:
      param_offload: true

  reward:
    reward_type: function
    compute_score: vision_reasoner

trainer:
  total_episodes: 1
  logger: ["console", "wandb"]
  project_name: VLReasoner
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 25
  test_freq: 100000
  val_before_train: false
  val_only: false
  find_last_checkpoint: true